name: zinsa
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-91.0.dev <4.0.0'
dependencies:
  http: ^1.1.2
  flutter:
    sdk: flutter
  firebase_core: ^2.20.0
  google_sign_in: ^6.1.6
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.13.2
  provider: ^6.1.1
  image_picker: ^1.0.4
  firebase_storage: ^11.5.5
  intl: ^0.18.1
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/appimages/google_logo.png
    - assets/appimages/pp.jpg
    

 