name: zinsa
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-91.0.dev <4.0.0'
dependencies:
  http: ^1.1.2
  flutter:
    sdk: flutter
  firebase_core: ^2.20.0
  flutter_plugin_android_lifecycle: ^2.0.17
  google_sign_in: ^6.1.6
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.13.2
  provider: ^6.1.1
  image_picker: ^1.0.4
  file_picker: ^8.0.0+1
  firebase_storage: ^11.5.5
  intl: ^0.18.1
  google_fonts: 6.1.0
  cupertino_icons: ^1.0.2
  firebase_messaging: ^14.7.15
  uuid: ^4.3.3
  shared_preferences: ^2.2.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/zinsa_logo.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/zinsa_logo.jpg"
    background_color: "#hexcode"
    theme_color: "#hexcode"

  
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/appimages/google_logo.png
    - assets/appimages/pp.jpg
