// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlGk2Kaehi5SGi5gqRY5FvgOgkLrlNKw4',
    appId: '1:828747139363:web:863fa465b866f73d416496',
    messagingSenderId: '828747139363',
    projectId: 'zinsa-app',
    authDomain: 'zinsa-app.firebaseapp.com',
    storageBucket: 'zinsa-app.appspot.com',
    measurementId: 'G-HBDGMGY8R6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5rrhN3GACNgL8X3m74Wi5Ylcc0JtY7G0',
    appId: '1:828747139363:android:1f116fe4baf98852416496',
    messagingSenderId: '828747139363',
    projectId: 'zinsa-app',
    storageBucket: 'zinsa-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3UDrjBKwyk6-fZC6RahYnjzpVDBTMifE',
    appId: '1:828747139363:ios:616afacb8b3c857c416496',
    messagingSenderId: '828747139363',
    projectId: 'zinsa-app',
    storageBucket: 'zinsa-app.appspot.com',
    iosClientId: '828747139363-keiln69ddr3ltl330n0mqec792rtbvd6.apps.googleusercontent.com',
    iosBundleId: 'com.example.zinsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3UDrjBKwyk6-fZC6RahYnjzpVDBTMifE',
    appId: '1:828747139363:ios:10b88c3cb13413ae416496',
    messagingSenderId: '828747139363',
    projectId: 'zinsa-app',
    storageBucket: 'zinsa-app.appspot.com',
    iosClientId: '828747139363-7j33vrvjdoa7de2lh944bt11rqmcr2vk.apps.googleusercontent.com',
    iosBundleId: 'com.example.zinsa.RunnerTests',
  );
}
